### ISSUE TITLE
Screener integration

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zeropool-relayer#132]
The relayer must make a request to screening service before processing sending a deposit transaction to rpc node.
The request must be made after all of the basic checks to exclude any possibility of redundant requests or DOS.

example request
```bash
curl --location --request POST 'https://url.thgkjlr.website/validate' \
--header 'Authorization: Bearer SECRET' \
--header 'Content-Type: application/json' \
--data-raw '  {
    "address": "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
  }'
```

example response:
```
{
    "result": false
}
```

If `result == false`,   the relayer must respond to to the client with a typed error, otherwise the process continues

**Comment by maikReal** [comment]
Will be released in 3.1.0 relayer version
