### ISSUE TITLE
Handle “more than 10000 logs returned” Infura error

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zeropool-relayer#45]
If a `eth_getLogs` request to Infura RPC provider is expected to return more than 10'000 logs, Infura response with an error containing “more than 10000 logs returned”. Consider to address the issue by recursively splitting block range in half and retrying two requests if such Infura response appears.

**Comment by LyzeOfKiel** [comment]
This issue is handled via configurable `EVENTS_PROCESSING_BATCH_SIZE` env.
