### ISSUE TITLE
Gas price oracles features propagation form tokenbridge

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zeropool-relayer#52]
Although the gas price oracle has been improved as part of the work on #32 consider to go through the corresponding implementation in the tokenbridge oracle to check that all features from it were propagated in the relayer code.

Here is the list of features:
- both upper and lower limits on gas prices (legacy gas price / priority fee / max fee per gas)
- configurable multiplicative factors on values returned by gas price oracles

**Comment by LyzeOfKiel** [comment]
Now, fee limit and multiplicative factors can be configured with env.
