### ISSUE TITLE
Relayer: Add more strict assertions on transaction proof verification {R7.11}

### ISSUE THREAD

**Issue by LyzeOfKiel** [zkBob/zeropool-relayer#62]
Now, relayer assumes that all public inputs provided by user for a transaction proof are correct. More strict assertion about the `root` public input should be made, as done in the [pool contract](https://github.com/zkBob/zkbob-contracts/blob/master/src/zkbob/utils/Parameters.sol#L16).
Possible solutions:
* Relayer should maintain a local root storage that corresponds to the pool contract and query it for the root corresponding to the provided index (part of `delta` public input parameter).
* Take a root by an index directly from the contract. But, there might be problems with optimistic state, as some transaction can depend on another transaction that is not mined yet.

**Comment by r0wdy1** [comment]
Since we're not allowing chaining the transaction I would suggest option 2

**Comment by ulyanas** [comment]
Need to check PR

**Comment by maikReal** [comment]
Better if we release this task earlier than 22.11
