### ISSUE TITLE
Add endpoints /params/*

### ISSUE THREAD

**Issue by akolotov** [zkBob/zeropool-relayer#63]
In order to [improve the UX](https://github.com/zkBob/zkbob-client-js/issues/30), it is required to implement endpoints `/params/hash/tx` and `/params/hash/tree` to receiving actual relayer’s parameters hashes (SHA256), e.g.:
```json
{
	"hash": "4a0a5571666b41216772ca8f4ac5c6fe37014169a21b0f33d893d2e1a0506e2f"
}
```

**Comment by ulyanas** [comment]
@vadimnikonov1  Please test in Console at Staging.

**Comment by akolotov** [comment]
Tests must be executed together with https://github.com/zkBob/libzeropool/pull/3

**Comment by ulyanas** [comment]
We decided to check only during the Ceremony 2.0
