### ISSUE TITLE
Re-consider cases when logging of stack trace is needed in validateTx.ts

### ISSUE THREAD

**Issue by akolotov** [zkBob/zeropool-relayer#64]
In order to optimize amount of useful information reported in the logs consider to go through the construction like `return new Error(...)` in https://github.com/zkBob/zeropool-relayer/blob/852601933a76de4011b7b2ac831b364782240dbe/zp-relayer/validateTx.ts and confirm which of them really needs to produce stack trances in the logs and where just a error/warning/info message is required.

**Comment by LyzeOfKiel** [comment]
Now, validation errors are considered as warnings
https://github.com/zkBob/zeropool-relayer/blob/devel/zp-relayer/utils/helpers.ts#L120-L121
