### ISSUE TITLE
Extend debug info with HTTP requests and response

### ISSUE THREAD

**Issue by akolotov** [zkBob/zeropool-relayer#67]
In order to simplify the debugging of the new issues consider to improve debug logs as so they explicitly note incoming HTTP requests and outgoing HTTP responses. There could be a filter which allows to specify which requests/responses should not be logged (e.g. `/`, `/info` and so on)

**Comment by LyzeOfKiel** [comment]
@akolotov @k1rill-fedoseev 
Currently all HTTP requests' info is logged in `zp.log` file. Should we still log this to console, as well?
If yes, then logging all requests' data may flood the logs as each line in `zp.log` is more than 500 characters. So, we need to omit some parts of it, e.g. request headers. Wdyt?

Link to recent discussion - https://github.com/zkBob/zeropool-relayer/pull/121#discussion_r1057266886

**Comment by k1rill-fedoseev** [comment]
I would personally prefer to have all logs in one place, with properly configured verbosity levels and fully in the JSON format, so that it would be easy to navigate and search through them
