### ISSUE TITLE
Relayer improvements {R20.12}

### ISSUE THREAD

**Issue by ulyanas** [zkBob/zeropool-relayer#72]
- [x] https://github.com/zkBob/zeropool-relayer/issues/28
- [x] https://github.com/zkBob/zeropool-relayer/issues/34
- [x] https://github.com/zkBob/zeropool-relayer/issues/35
- [x] https://github.com/zkBob/zeropool-relayer/issues/43
- [x] https://github.com/zkBob/zeropool-relayer/issues/56
- [x] https://github.com/zkBob/zeropool-relayer/issues/57
- [x] https://github.com/zkBob/zeropool-relayer/issues/58

**Comment by ulyanas** [comment]
@LyzeOfKiel  Will update status

**Comment by r0wdy1** [comment]
Postponed till next release

**Comment by ulyanas** [comment]
eta 1d
