### ISSUE TITLE
Fix transaction resending in sentTxWorker {R7.11}

### ISSUE THREAD

**Issue by LyzeOfKiel** [zkBob/zeropool-relayer#74]
Now, in case transaction is not mined, after gas price is updated in transaction config, transaction is not resent. After some time, such transactions can be lost in the mempool.
Need to add resend functionality in the `sentTxWorker.ts` after updating gas price config.

https://github.com/zkBob/zeropool-relayer/blob/3900473042ede50540cad8b9a4c4af7aae85c37f/zp-relayer/workers/sentTxWorker.ts#L125-L130

**Comment by vadimnikonov1** [comment]
QA review - OK
